pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/Nagendra27014/learning_devops.git',
                    branch: 'main',
                    credentialsId: '1b9ce9a7-abba-4897-b473-0451775ab972'
            }
        }

        stage('Build') {
            steps {
                echo "Build started"
            }
        }
    }
}
